name: PR Builder

on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches: [master]
    paths-ignore:
      - "**.md"
      - "LICENSE"

concurrency:
  group: pr-builder-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: 🚧 PR Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [lts/*]
        pnpm-version: [8.7.4]
        maven-version: [3.8.6]
        java-version: [11]
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      - name: 🟢 Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: 🐳 Set SHAs for Nx
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: "master"

      - name: 🥡 Setup pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: 🎈 Get pnpm store directory
        id: get-pnpm-cache-dir
        run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: 🔆 Cache pnpm modules
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.get-pnpm-cache-dir.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 🧩 Install Dependencies
        run: pnpm install

      - name: 🦄 Lint Changed Files
        run: bash ./scripts/lint-changed.sh ${{ github.event.pull_request.number }}

      # Temporarily disable linting all files as it is failing intermittently.
      # - name: ⏳ Lint All Files
      #   run: pnpm nx affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --plain --target=lint --parallel=3

      - name: 👷 Build Re-usable Modules
        run: pnpm build:modules

      - name: ☄️ Check Type Errors
        run: pnpm nx affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --target=typecheck --parallel=3

      - name: 🃏 Run Jest & Collect Coverage
        run: pnpm test:unit

      - name: ☕ Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "adopt"
          cache: maven

      - name: 🦩 Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: ${{ matrix.maven-version }}

      - name: 🧩 Install Dependencies
        run: pnpm install

      - name: 👷 PNPM Build
        run: pnpm build

      - name: 🏗️ Maven Build identity-apps-core
        run: |
          cd identity-apps-core
          mvn clean install -U -Dlint.exec.skip=true -Dbootstrap.exec.skip=true

      - name: 💾 Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 🤖 Aggregate Test Coverage
        if: false
        run: |
          pnpm test:unit:coverage:aggregate
          pnpm nyc:text-summary-report
          pnpm nyc:text-report
